/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookRouteImport } from './routes/book'
import { Route as BookingConfirmedRouteImport } from './routes/booking-confirmed'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as ExamsRouteImport } from './routes/exams'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as HomeRouteImport } from './routes/home'
import { Route as InterviewRouteImport } from './routes/interview'
import { Route as InterviewStatusRouteImport } from './routes/interview-status'
import { Route as LanguageRouteImport } from './routes/language'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OtpRouteImport } from './routes/otp'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ResultRouteImport } from './routes/result'
import { Route as SystemCheckRouteImport } from './routes/system-check'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminDrivesRouteImport } from './routes/admin.drives'
import { Route as AdminFairnessRouteImport } from './routes/admin.fairness'
import { Route as OpportunitiesIndexRouteImport } from './routes/opportunities.index'
import { Route as OpportunitiesIdRouteImport } from './routes/opportunities.$id'
import { Route as AdminCandidatesIndexRouteImport } from './routes/admin.candidates.index'
import { Route as AdminCandidatesIdRouteImport } from './routes/admin.candidates.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingConfirmedRoute = BookingConfirmedRouteImport.update({
  id: '/booking-confirmed',
  path: '/booking-confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsRoute = ExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewRoute = InterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewStatusRoute = InterviewStatusRouteImport.update({
  id: '/interview-status',
  path: '/interview-status',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageRoute = LanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpRoute = OtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemCheckRoute = SystemCheckRouteImport.update({
  id: '/system-check',
  path: '/system-check',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDrivesRoute = AdminDrivesRouteImport.update({
  id: '/admin/drives',
  path: '/admin/drives',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFairnessRoute = AdminFairnessRouteImport.update({
  id: '/admin/fairness',
  path: '/admin/fairness',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesIndexRoute = OpportunitiesIndexRouteImport.update({
  id: '/opportunities/',
  path: '/opportunities/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesIdRoute = OpportunitiesIdRouteImport.update({
  id: '/opportunities/$id',
  path: '/opportunities/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCandidatesIndexRoute = AdminCandidatesIndexRouteImport.update({
  id: '/admin/candidates/',
  path: '/admin/candidates/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCandidatesIdRoute = AdminCandidatesIdRouteImport.update({
  id: '/admin/candidates/$id',
  path: '/admin/candidates/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/booking-confirmed': typeof BookingConfirmedRoute
  '/documents': typeof DocumentsRoute
  '/exams': typeof ExamsRoute
  '/feedback': typeof FeedbackRoute
  '/home': typeof HomeRoute
  '/interview': typeof InterviewRoute
  '/interview-status': typeof InterviewStatusRoute
  '/language': typeof LanguageRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/otp': typeof OtpRoute
  '/profile': typeof ProfileRoute
  '/result': typeof ResultRoute
  '/system-check': typeof SystemCheckRoute
  '/timeline': typeof TimelineRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/drives': typeof AdminDrivesRoute
  '/admin/fairness': typeof AdminFairnessRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/admin/': typeof AdminIndexRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
  '/admin/candidates/$id': typeof AdminCandidatesIdRoute
  '/admin/candidates/': typeof AdminCandidatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/booking-confirmed': typeof BookingConfirmedRoute
  '/documents': typeof DocumentsRoute
  '/exams': typeof ExamsRoute
  '/feedback': typeof FeedbackRoute
  '/home': typeof HomeRoute
  '/interview': typeof InterviewRoute
  '/interview-status': typeof InterviewStatusRoute
  '/language': typeof LanguageRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/otp': typeof OtpRoute
  '/profile': typeof ProfileRoute
  '/result': typeof ResultRoute
  '/system-check': typeof SystemCheckRoute
  '/timeline': typeof TimelineRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/drives': typeof AdminDrivesRoute
  '/admin/fairness': typeof AdminFairnessRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/admin': typeof AdminIndexRoute
  '/opportunities': typeof OpportunitiesIndexRoute
  '/admin/candidates/$id': typeof AdminCandidatesIdRoute
  '/admin/candidates': typeof AdminCandidatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/booking-confirmed': typeof BookingConfirmedRoute
  '/documents': typeof DocumentsRoute
  '/exams': typeof ExamsRoute
  '/feedback': typeof FeedbackRoute
  '/home': typeof HomeRoute
  '/interview': typeof InterviewRoute
  '/interview-status': typeof InterviewStatusRoute
  '/language': typeof LanguageRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/otp': typeof OtpRoute
  '/profile': typeof ProfileRoute
  '/result': typeof ResultRoute
  '/system-check': typeof SystemCheckRoute
  '/timeline': typeof TimelineRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/drives': typeof AdminDrivesRoute
  '/admin/fairness': typeof AdminFairnessRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/admin/': typeof AdminIndexRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
  '/admin/candidates/$id': typeof AdminCandidatesIdRoute
  '/admin/candidates/': typeof AdminCandidatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book'
    | '/booking-confirmed'
    | '/documents'
    | '/exams'
    | '/feedback'
    | '/home'
    | '/interview'
    | '/interview-status'
    | '/language'
    | '/login'
    | '/notifications'
    | '/otp'
    | '/profile'
    | '/result'
    | '/system-check'
    | '/timeline'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/drives'
    | '/admin/fairness'
    | '/opportunities/$id'
    | '/admin/'
    | '/opportunities/'
    | '/admin/candidates/$id'
    | '/admin/candidates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book'
    | '/booking-confirmed'
    | '/documents'
    | '/exams'
    | '/feedback'
    | '/home'
    | '/interview'
    | '/interview-status'
    | '/language'
    | '/login'
    | '/notifications'
    | '/otp'
    | '/profile'
    | '/result'
    | '/system-check'
    | '/timeline'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/drives'
    | '/admin/fairness'
    | '/opportunities/$id'
    | '/admin'
    | '/opportunities'
    | '/admin/candidates/$id'
    | '/admin/candidates'
  id:
    | '__root__'
    | '/'
    | '/book'
    | '/booking-confirmed'
    | '/documents'
    | '/exams'
    | '/feedback'
    | '/home'
    | '/interview'
    | '/interview-status'
    | '/language'
    | '/login'
    | '/notifications'
    | '/otp'
    | '/profile'
    | '/result'
    | '/system-check'
    | '/timeline'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/drives'
    | '/admin/fairness'
    | '/opportunities/$id'
    | '/admin/'
    | '/opportunities/'
    | '/admin/candidates/$id'
    | '/admin/candidates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookRoute: typeof BookRoute
  BookingConfirmedRoute: typeof BookingConfirmedRoute
  DocumentsRoute: typeof DocumentsRoute
  ExamsRoute: typeof ExamsRoute
  FeedbackRoute: typeof FeedbackRoute
  HomeRoute: typeof HomeRoute
  InterviewRoute: typeof InterviewRoute
  InterviewStatusRoute: typeof InterviewStatusRoute
  LanguageRoute: typeof LanguageRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  OtpRoute: typeof OtpRoute
  ProfileRoute: typeof ProfileRoute
  ResultRoute: typeof ResultRoute
  SystemCheckRoute: typeof SystemCheckRoute
  TimelineRoute: typeof TimelineRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminDrivesRoute: typeof AdminDrivesRoute
  AdminFairnessRoute: typeof AdminFairnessRoute
  OpportunitiesIdRoute: typeof OpportunitiesIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  OpportunitiesIndexRoute: typeof OpportunitiesIndexRoute
  AdminCandidatesIdRoute: typeof AdminCandidatesIdRoute
  AdminCandidatesIndexRoute: typeof AdminCandidatesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-confirmed': {
      id: '/booking-confirmed'
      path: '/booking-confirmed'
      fullPath: '/booking-confirmed'
      preLoaderRoute: typeof BookingConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams': {
      id: '/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof ExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview': {
      id: '/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof InterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview-status': {
      id: '/interview-status'
      path: '/interview-status'
      fullPath: '/interview-status'
      preLoaderRoute: typeof InterviewStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/language': {
      id: '/language'
      path: '/language'
      fullPath: '/language'
      preLoaderRoute: typeof LanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp': {
      id: '/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof OtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-check': {
      id: '/system-check'
      path: '/system-check'
      fullPath: '/system-check'
      preLoaderRoute: typeof SystemCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/drives': {
      id: '/admin/drives'
      path: '/admin/drives'
      fullPath: '/admin/drives'
      preLoaderRoute: typeof AdminDrivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/fairness': {
      id: '/admin/fairness'
      path: '/admin/fairness'
      fullPath: '/admin/fairness'
      preLoaderRoute: typeof AdminFairnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/': {
      id: '/opportunities/'
      path: '/opportunities'
      fullPath: '/opportunities/'
      preLoaderRoute: typeof OpportunitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/$id': {
      id: '/opportunities/$id'
      path: '/opportunities/$id'
      fullPath: '/opportunities/$id'
      preLoaderRoute: typeof OpportunitiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/candidates/': {
      id: '/admin/candidates/'
      path: '/admin/candidates'
      fullPath: '/admin/candidates/'
      preLoaderRoute: typeof AdminCandidatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/candidates/$id': {
      id: '/admin/candidates/$id'
      path: '/admin/candidates/$id'
      fullPath: '/admin/candidates/$id'
      preLoaderRoute: typeof AdminCandidatesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookRoute: BookRoute,
  BookingConfirmedRoute: BookingConfirmedRoute,
  DocumentsRoute: DocumentsRoute,
  ExamsRoute: ExamsRoute,
  FeedbackRoute: FeedbackRoute,
  HomeRoute: HomeRoute,
  InterviewRoute: InterviewRoute,
  InterviewStatusRoute: InterviewStatusRoute,
  LanguageRoute: LanguageRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  OtpRoute: OtpRoute,
  ProfileRoute: ProfileRoute,
  ResultRoute: ResultRoute,
  SystemCheckRoute: SystemCheckRoute,
  TimelineRoute: TimelineRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminDrivesRoute: AdminDrivesRoute,
  AdminFairnessRoute: AdminFairnessRoute,
  OpportunitiesIdRoute: OpportunitiesIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  OpportunitiesIndexRoute: OpportunitiesIndexRoute,
  AdminCandidatesIdRoute: AdminCandidatesIdRoute,
  AdminCandidatesIndexRoute: AdminCandidatesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
